## Session 1 Homework

### Question 1
What's the version of Numpy that you installed?

In [39]:
import numpy as np
np.__version__

'1.21.5'

### Importing the Data

In [40]:
import pandas as pd
df = pd.read_csv('car_price.txt')
df.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

### Question 2
How many records are in the dataset?

In [41]:
print(f"The total number of rows in the data are : {df.shape[0]}")

The total number of rows in the data are : 11914


### Question 3
Who are the most frequent car manufacturers (top-3) according to the dataset?

In [93]:
print("The most frequnt car manufacturers according to the dataset are ==>")
print(df['Make'].value_counts()[0:3])

The most frequnt car manufacturers according to the dataset are ==>
Chevrolet     1123
Ford           881
Volkswagen     809
Name: Make, dtype: int64


### Question 4
What's the number of unique Audi car models in the dataset?

In [57]:
df_audi = df[df['Make'] == 'Audi']
print(f"The number of unique Audi car models in the dataset are : {df_audi['Model'].nunique()}")

The number of unique Audi car models in the dataset are : 34


### Question 5
How many columns in the dataset have missing values?

In [76]:
li_null = df.columns[df.isnull().any()].tolist()
print(f"The total number of columns in the dataset with missing values are : {len(li_null)}")

The total number of columns in the dataset with missing values are : 5


### Question 6
1. Find the median value of "Engine Cylinders" column in the dataset.
2. Next, calculate the most frequent value of the same "Engine Cylinders".
3. Use the fillna method to fill the missing values in "Engine Cylinders" with the most frequent value from the previous step.
4. Now, calculate the median value of "Engine Cylinders" once again.
Has it changed?

In [110]:
# Find the median value of "Engine Cylinders" column in the dataset.
print(f"Median of Engine Cylinders field : {df['Engine Cylinders'].median()}")

Median of Engine Cylinders field : 6.0


In [95]:
# Next, calculate the most frequent value of the same "Engine Cylinders".
df['Engine Cylinders'].value_counts()

4.0     4752
6.0     4489
8.0     2031
12.0     230
5.0      225
10.0      68
0.0       56
3.0       30
16.0       3
Name: Engine Cylinders, dtype: int64

### The most frequent value is 4.0.

In [104]:
# Use the fillna method to fill the missing values in "Engine Cylinders" with the most frequent value from the previous step.
df['Engine Cylinders'] = df['Engine Cylinders'].fillna(4.0)

In [109]:
# Now, calculate the median value of "Engine Cylinders" once again
print(f"Median after imputing the null values with the most occuring value : {df['Engine Cylinders'].median()}")

Median after imputing the null values with the most occuring value : 6.0


### The Median does not change even after filling the null values with the most occuring value.

### Question 7
1. Select all the "Lotus" cars from the dataset.
2. Select only columns "Engine HP", "Engine Cylinders".
3. Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 9 rows).
4. Get the underlying NumPy array. Let's call it X.
5. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
6. Invert XTX.
7. Create an array y with values [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800].
8. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
9. What's the value of the first element of w?

In [134]:
# Select all the "Lotus" cars from the dataset.
df_l = df[df['Make'] == 'Lotus']
df_l['Make'].unique()

array(['Lotus'], dtype=object)

In [137]:
# Select only columns "Engine HP", "Engine Cylinders".
df_l_2 = df_l[['Engine HP', 'Engine Cylinders']]
df_l_2.head()

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3914      189.0               4.0
3915      189.0               4.0
3916      218.0               4.0

In [138]:
# Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 9 rows).
df_l_2.drop_duplicates(inplace=True)
df_l_2

C:\Users\91635\AppData\Local\Temp\ipykernel_27708\1837799781.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_l_2.drop_duplicates(inplace=True)


Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3918      217.0               4.0
4216      350.0               8.0
4257      400.0               6.0
4259      276.0               6.0
4262      345.0               6.0
4292      257.0               4.0
4293      240.0               4.0

In [165]:
# Get the underlying NumPy array. Let's call it X.
X = np.array(df_l_2)
X

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

In [167]:
# Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
XT = np.transpose(X)
print(XT)
XTX = np.matmul(XT, X)
print(XTX)


[[189. 218. 217. 350. 400. 276. 345. 257. 240.]
 [  4.   4.   4.   8.   6.   6.   6.   4.   4.]]
[[7.31684e+05 1.34100e+04]
 [1.34100e+04 2.52000e+02]]


In [174]:
# Invert XTX
XTX_I = np.linalg.inv(XTX)
XTX_I

array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

In [171]:
# Create an array y with values [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800]
y = np.array([1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800])
y

array([1100,  800,  750,  850, 1300, 1000, 1000, 1300,  800])

In [175]:
# Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
temp = np.matmul(XTX_I, XT)
w = np.dot(temp, y)
print(f"The value of the first element of w is : {w[0]}")

The value of the first element of w is : 4.594944810094551
